[package]
name = "chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tungstenite = "0.13.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
tokio-tungstenite = "0.18.0"
warp = "0.3.5"
futures-util = "0.3.28"
futures = "0.3.28"
futures-channel = "0.3.28"
anyhow = "1.0.44"
tokio-stream = "0.1.14"


